title: M&S compute server documentation
description: User, admin, and configuration documentation for the M&S department compute server
show_downloads: false

remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
